# Problem set: Tensorflow
 These problems relate to the Python package Tensorflow.

# 1. Use Tensorflow to create model
  Use Tensorflow to create a model to predict the species of Iris from a flower’s sepal width, sepal length, petal width, and petal length.

In [2]:
import numpy as np
import csv
import keras as kr
import tensorflow as tf 
import sklearn.cross_validation as cv
iris = list(csv.reader(open('iris.csv')))[1:]
# The inputs are four floats: sepal length, sepal width, petal length, petal width.
inputs  = np.array(iris)[:,:4].astype(np.float)
 #Outputs are initially individual strings: setosa, versicolor or virginica.
outputs = np.array(iris)[:,4]
# Convert the output strings to ints.
outputs_vals, outputs_ints = np.unique(outputs, return_inverse=True)
# Encode the category integers as binary categorical vairables.
outputs_cats = kr.utils.to_categorical(outputs_ints)
iris

[['5.1', '3.5', '1.4', '0.2', 'setosa'],
 ['4.9', '3.0', '1.4', '0.2', 'setosa'],
 ['4.7', '3.2', '1.3', '0.2', 'setosa'],
 ['4.6', '3.1', '1.5', '0.2', 'setosa'],
 ['5.0', '3.6', '1.4', '0.2', 'setosa'],
 ['5.4', '3.9', '1.7', '0.4', 'setosa'],
 ['4.6', '3.4', '1.4', '0.3', 'setosa'],
 ['5.0', '3.4', '1.5', '0.2', 'setosa'],
 ['4.4', '2.9', '1.4', '0.2', 'setosa'],
 ['4.9', '3.1', '1.5', '0.1', 'setosa'],
 ['5.4', '3.7', '1.5', '0.2', 'setosa'],
 ['4.8', '3.4', '1.6', '0.2', 'setosa'],
 ['4.8', '3.0', '1.4', '0.1', 'setosa'],
 ['4.3', '3.0', '1.1', '0.1', 'setosa'],
 ['5.8', '4.0', '1.2', '0.2', 'setosa'],
 ['5.7', '4.4', '1.5', '0.4', 'setosa'],
 ['5.4', '3.9', '1.3', '0.4', 'setosa'],
 ['5.1', '3.5', '1.4', '0.3', 'setosa'],
 ['5.7', '3.8', '1.7', '0.3', 'setosa'],
 ['5.1', '3.8', '1.5', '0.3', 'setosa'],
 ['5.4', '3.4', '1.7', '0.2', 'setosa'],
 ['5.1', '3.7', '1.5', '0.4', 'setosa'],
 ['4.6', '3.6', '1.0', '0.2', 'setosa'],
 ['5.1', '3.3', '1.7', '0.5', 'setosa'],
 ['4.8', '3.4', 

## 2.Split the data into training and testing
  Split the data set into a training set and a testing set,you can write some code to randomly separate the data on the fly.
  

In [8]:
##in_train,in_test,out_train,out_test = cv.train_test_split(inputs,outputs,trian_size=0.5,random_state=1)
   ## uniq_test,ids_test = np.unique(out_test,return_inverse=True)
    ##uniq_train,ids_train = np.unique(out_test,return_inverse=True)
    
 ## adapted from https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html
## adapted from https://docs.scipy.org/doc/numpy/reference/generated/numpy.array_split.html
inds = np.random.permutation(len(inputs))## Returns a random permutation
train_inds, test_inds = np.array_split(inds, 2)
## np.array_split(inds,2) 
inputs_train, outputs_train = inputs[train_inds], outputs_cats[train_inds]
inputs_test,  outputs_test  = inputs[test_inds],  outputs_cats[test_inds]
print(inputs_train)

[[ 6.7  3.1  4.7  1.5]
 [ 5.4  3.9  1.7  0.4]
 [ 4.9  3.1  1.5  0.2]
 [ 6.2  2.2  4.5  1.5]
 [ 6.4  3.2  4.5  1.5]
 [ 6.8  3.   5.5  2.1]
 [ 6.7  2.5  5.8  1.8]
 [ 6.4  2.9  4.3  1.3]
 [ 7.1  3.   5.9  2.1]
 [ 5.6  2.5  3.9  1.1]
 [ 5.1  3.5  1.4  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 5.5  2.5  4.   1.3]
 [ 6.7  3.   5.   1.7]
 [ 6.   2.2  5.   1.5]
 [ 6.5  3.   5.5  1.8]
 [ 6.2  3.4  5.4  2.3]
 [ 4.9  3.   1.4  0.2]
 [ 6.5  2.8  4.6  1.5]
 [ 5.2  3.4  1.4  0.2]
 [ 6.9  3.1  4.9  1.5]
 [ 5.9  3.   5.1  1.8]
 [ 6.5  3.2  5.1  2. ]
 [ 4.4  3.2  1.3  0.2]
 [ 6.3  2.8  5.1  1.5]
 [ 5.6  3.   4.5  1.5]
 [ 6.9  3.1  5.4  2.1]
 [ 5.8  2.7  5.1  1.9]
 [ 5.5  3.5  1.3  0.2]
 [ 6.4  2.8  5.6  2.1]
 [ 5.   3.2  1.2  0.2]
 [ 7.2  3.6  6.1  2.5]
 [ 4.8  3.1  1.6  0.2]
 [ 6.9  3.2  5.7  2.3]
 [ 5.7  2.5  5.   2. ]
 [ 5.   3.5  1.6  0.6]
 [ 6.1  3.   4.6  1.4]
 [ 7.7  3.   6.1  2.3]
 [ 5.8  2.7  4.1  1. ]
 [ 5.1  3.4  1.5  0.2]
 [ 5.1  3.8  1.9  0.4]
 [ 5.6  3.   4.1  1.3]
 [ 6.8  3.2  5.9  2.3]
 [ 5.4  3.9

## 3.Train the model

In [4]:
# Create a neural network.
model = kr.models.Sequential()

# Add an initial layer with 4 input nodes, and a hidden layer with 16 nodes.
model.add(kr.layers.Dense(16, input_shape=(4,)))
# Apply the sigmoid activation function to that layer.
model.add(kr.layers.Activation("sigmoid"))
# Add another layer, connected to the layer with 16 nodes, containing three output nodes.
model.add(kr.layers.Dense(3))
# Use the softmax activation function there.
model.add(kr.layers.Activation("softmax"))

# Configure the model for training.
# Uses the adam optimizer and categorical cross entropy as the loss function.
# Add in some extra metrics - accuracy being the only one.
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

# Fit the model using our training data.
model.fit(inputs_train, outputs_train, epochs=100, batch_size=1, verbose=1)

# Evaluate the model using the test data set.
loss, accuracy = model.evaluate(inputs_test, outputs_test, verbose=1)

# Output the accuracy of the model.
print("\n\nLoss: %6.4f\tAccuracy: %6.4f" % (loss, accuracy))

# Predict the class of a single flower.
prediction = np.around(model.predict(np.expand_dims(inputs_test[0], axis=0))).astype(np.int)[0]
print("Actual: %s\tEstimated: %s" % (outputs_test[0].astype(np.int), prediction))
print("That means it's a %s" % outputs_vals[prediction.astype(np.bool)][0])


Epoch 1/100
75/75 [==============================] - 0s - loss: 1.2170 - acc: 0.3200         
Epoch 2/100
75/75 [==============================] - 0s - loss: 1.1447 - acc: 0.3067     
Epoch 3/100
75/75 [==============================] - 0s - loss: 1.1191 - acc: 0.3733        
Epoch 4/100
75/75 [==============================] - 0s - loss: 1.0952 - acc: 0.3600        
Epoch 5/100
75/75 [==============================] - 0s - loss: 1.0693 - acc: 0.3467     
Epoch 6/100
75/75 [==============================] - 0s - loss: 1.0439 - acc: 0.3867     
Epoch 7/100
75/75 [==============================] - 0s - loss: 1.0215 - acc: 0.4533        
Epoch 8/100
75/75 [==============================] - 0s - loss: 0.9999 - acc: 0.6133        
Epoch 9/100
75/75 [==============================] - 0s - loss: 0.9732 - acc: 0.6667        
Epoch 10/100
75/75 [==============================] - 0s - loss: 0.9505 - acc: 0.8133     
Epoch 11/100
75/75 [==============================] - 0s - loss: 0.9197 - acc: 0

75/75 [==============================] - 0s - loss: 0.2128 - acc: 0.9467     
Epoch 91/100
75/75 [==============================] - 0s - loss: 0.2130 - acc: 0.9467     
Epoch 92/100
75/75 [==============================] - 0s - loss: 0.2154 - acc: 0.9733     
Epoch 93/100
75/75 [==============================] - 0s - loss: 0.2079 - acc: 0.9600     
Epoch 94/100
75/75 [==============================] - 0s - loss: 0.2063 - acc: 0.9733     
Epoch 95/100
75/75 [==============================] - 0s - loss: 0.2036 - acc: 0.9600     
Epoch 96/100
75/75 [==============================] - 0s - loss: 0.2027 - acc: 0.9600     
Epoch 97/100
75/75 [==============================] - 0s - loss: 0.1992 - acc: 0.9867     
Epoch 98/100
75/75 [==============================] - 0s - loss: 0.1951 - acc: 0.9600     
Epoch 99/100
75/75 [==============================] - 0s - loss: 0.1962 - acc: 0.9467        
Epoch 100/100
32/75 [===========>..................] - ETA: 0s

Loss: 0.1389	Accuracy: 0.9867
Actual

## 4.Test the mode